blueprint:
  name: Sync Sensor Value to Climate Setpoints
  description: >
    Use a sensor (e.g., input_number, MQTT, external system) to control one or more climate entities'
    target temperature. This triggers when the sensor changes.
  domain: automation
  input:
    source_sensor:
      name: Source Temperature Sensor
      selector:
        entity:
          domain: sensor
    target_climates:
      name: Target Climate Entities
      selector:
        entity:
          domain: climate
          multiple: true

trigger:
  - platform: state
    entity_id: !input source_sensor

condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.state | float(default=0) > 0 }}

action:
  - service: climate.set_temperature
    data:
      temperature: "{{ states(source_sensor) | float }}"
    target:
      entity_id: !input target_climates

mode: parallel
